environment:
  matrix:
    - platform: x64
      CONDAPATH: C:\Miniconda-x64
      PYVER: 3.6

    - platform: x86
      CONDAPATH: C:\Miniconda
      PYVER: 3.6

build_script:
  - '%CONDAPATH%\Scripts\conda config --set always_yes yes'
  - '%CONDAPATH%\Scripts\conda update conda'
  - '%CONDAPATH%\Scripts\conda create -p C:\pythontest python=%PYVER%'
  - '%CONDAPATH%\Scripts\activate C:\pythontest'
  - where python
  - python -m pip install --upgrade pip
  - python -m pip install nose cvxpy scs numpy scipy
  - python -m pip install .

test_script:
  - nosetests

notifications:
  - provider: Email
    to:
      - stbarratt@gmail.com
      - akshaykagrawal7@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true