language: python
os: linux
install:
  - pip install --upgrade pip
  - pip install nose
  - pip install .
script:
  - nosetests
notifications:
  email:
    - stbarratt@gmail.com
    - akshaykagrawal7@gmail.com