matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=3.5
  - os: osx
    language: generic
    env: PYTHON=3.6
  - os: osx
    language: generic
    env: PYTHON=3.7
  - os: linux
    dist: xenial
    language: python
    python: "3.5"
  - os: linux
    dist: xenial
    language: python
    python: "3.6"
  - os: linux
    dist: xenial
    language: python
    python: "3.7"
  - os: linux
    dist: bionic
    language: python
    python: "3.5"
  - os: linux
    dist: bionic
    language: python
    python: "3.6"
  - os: linux
    dist: bionic
    language: python
    python: "3.7"

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install liblapack-dev;
      elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew update;
        brew install pyenv-virtualenv gcc openssl;
        export CFLAGS="-I$(brew --prefix openssl)/include ${CFLAGS}";
        export LDFLAGS="-L$(brew --prefix openssl)/lib ${LDFLAGS}";
        pyenv install $PYTHON;
        export PYENV_VERSION=$PYTHON;
        export PATH="/Users/travis/.pyenv/shims:${PATH}";
        pyenv virtualenv testenv;
        python --version;
      fi

install:
  - pip install --upgrade pip
  - pip install nose cvxpy scs numpy scipy
  - pip install .

script:
  - nosetests

notifications:
  email:
    - stbarratt@gmail.com
    - akshaykagrawal7@gmail.com