language: python
os: linux
before_install:
  sudo apt-get install liblapack-dev
install:
  - pip install --upgrade pip
  - pip install nose cvxpy scs
  - pip install .
script:
  - nosetests
notifications:
  email:
    - stbarratt@gmail.com
    - akshaykagrawal7@gmail.com