language: python
os: linux
before_install:
  - sudo apt-get install liblapack-dev
  - eval CC=gcc-7 && CXX=g++-7
install:
  - pip install --upgrade pip
  - pip install nose cvxpy scs numpy scipy
  - pip install .
script:
  - nosetests -v --nocapture
notifications:
  email:
    - stbarratt@gmail.com
    - akshaykagrawal7@gmail.com