# TODO add osx
matrix:
  include:
  - os: linux
    dist: xenial
    language: python
    python: "3.5"
  - os: linux
    dist: xenial
    language: python
    python: "3.6"
  - os: linux
    dist: xenial
    language: python
    python: "3.7"
  - os: linux
    dist: bionic
    language: python
    python: "3.5"
  - os: linux
    dist: bionic
    language: python
    python: "3.6"
  - os: linux
    dist: bionic
    language: python
    python: "3.7"

before_install:
  - sudo apt-get install liblapack-dev;

install:
  - pip install --upgrade pip
  - pip install --upgrade numpy
  - pip install nose scipy scs cvxpy
  - pip install .

script:
  - nosetests

notifications:
  email:
    - stbarratt@gmail.com
    - akshaykagrawal7@gmail.com
