language: python
os: linux
before_install:
  - eval CC=gcc-7 && CXX=g++-7
  - sudo apt install -y liblapack-dev
install:
  - pip install --upgrade pip
  - pip install nose cvxpy scs numpy scipy
  - pip install .
script:
  - nosetests
notifications:
  email:
    - stbarratt@gmail.com
    - akshaykagrawal7@gmail.com